name: "Beta Release"

on:
  push:
    branches:
      - release-main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - uses: goreleaser/goreleaser-action@v3
        env:
          GORELEASER_CURRENT_TAG: v0.3.0
        with:
          version: latest
          args: release --rm-dist --snapshot

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          automatic_release_tag: "latest"
          prerelease: true
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          files: |
            dist/*.tar.gz
            dist/*.zip
            dist/checksums.txt